import { ConfigProvider } from "antd"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <ConfigProvider
        theme={{
          components: {
            "Input": {
              "activeBorderColor": "rgb(245,97,0)",
              "hoverBorderColor": "rgb(245,97,0)",
            }
          },
        }}
      >

        {children}

      </ConfigProvider>
    </div>
  )
}
