/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { mainTheme } from "@/theme/ant-theme";
import ReduxProviders from "@/utils/ReduxProviders";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
      <ConfigProvider theme={mainTheme as any}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}
          monica-id="ofpnmcalabcbjgholdjcjblkibolbppb"
          monica-version="7.9.1"
          cz-shortcut-listen="true"
          data-gr-ext-installed=""
          data-new-gr-c-s-check-loaded="14.1252.0"
        >
          <ReduxProviders>
            {children}
          </ReduxProviders>
        </body>
      </ConfigProvider>
    </html >
  );
}
